[tool.ruff]

show-fixes = true
target-version = "py37"
line-length = 79
indent-width = 4



[tool.ruff.lint]
extend-select = ["C4", "SIM", "TCH"]
ignore = []
# Add "Q" to the list of enabled codes.
select = ["E4", "E5", "E7", "E9", "F", "Q"]

